spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: dbpassword!
  jpa:
    show-sql: true
  mail:
    username: gwozdeckidaniel@gmail.com
server:
  port: 8082
websiteUrl: http://localhost:4242